version: '3.1'

services:
  nginx:
    container_name: app_nginx
    image: nginx:latest
    links:
      - php:app_php@
    depends_on:
      - php
      - db

  php:
    container_name: app_php
    image: lima195/php-fpm-${PHP_VERSION}:lastest
    depends_on:
      - db

  adminer:
    container_name: app_adminer
    image: adminer
    links:
      - db

  db:
    container_name: app_mysql
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: app_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: app_rabbitmq
    