# Docker Lemp for Magento applications
version: '3.1'

services:
  nginx:
    container_name: app_nginx
    image: nginx:latest
    working_dir: ${WORKING_DIR}
    links:
      - php:app_php@
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,cached
      - ${WWW_DIR}:${WORKING_DIR}
    depends_on:
      - php
      - db
    networks:
      - esnet
    ports:
      - 80:80

  php:
    container_name: app_php
    #image: lima195/php-fpm-${PHP_VERSION}-laravel:lastest
    # Develop porpuses
    build:
      context: .
      dockerfile: ./php/${PHP_VERSION}/Dockerfile
    volumes:
      - ./php/${PHP_VERSION}/${LOCAL_PHP_INI}:${DOCKER_PHP_INI}
      - ./php/${PHP_VERSION}/${LOCAL_PHP_XDEBUG_INI}:${DOCKER_PHP_XDEBUG_INI}
      - ${WWW_DIR}:${WORKING_DIR}
    # command: sh -c "/home/john/go/bin/MailHog"
    user: john
    working_dir: ${WORKING_DIR}
    depends_on:
      - db
    networks:
      - esnet
    ports:
      - 8025:8025

  adminer:
    container_name: app_adminer
    image: adminer
    links:
      - db
    networks:
      - esnet
    ports:
      - 8080:8080

  db:
    container_name: app_mysql
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - esnet
    ports:
      - 3306:3306

  # redis:
  #   container_name: app_redis
  #   image: redis:${REDIS_VERSION}
  #   command: redis-server --requirepass ${REDIS_PASS}
  #   volumes:
  #     - ./volumes/redis/data:/data
  #   networks:
  #     - esnet
  #   ports:
  #     - 6379:6379
  #     - 6380:6380
  #     - 6381:6381

# volumes:
#   rabbitmqvolume:
#     driver: local

networks:
  esnet:
