# Docker Lemp for Magento applications
version: "3.1"

services:
  nginx:
    # build:
    #   context: .
    #   dockerfile: ./nginx/${NGINX_VERSION}/Dockerfile
    working_dir: ${WORKING_DIR}

  php:
    # command: sh -c "/home/john/go/bin/MailHog"
    # Develop porpuses
    # build:
    #   context: .
    #   dockerfile: ./php/${PHP_VERSION}/Dockerfile
    user: john
    working_dir: ${WORKING_DIR}

  db:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  elasticsearch:
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
